fix: update env issues within examples, cosmetic changes to the README, minor fixes within models
toolhouseai/toolhouse-sdk-python pull request #11
Opened 2024-11-28 01:33 UTC by aaishikasb

This PR:
- fixes issues with accessing environment variables in all the sample applications inside examples
- adds cosmetic changes to the README
- updates LLMs for some of the applications

2024-11-28 01:41 UTC, pulphix commented on examples/sample_anthropic_stream.py
> +th = Toolhouse(access_token=TH_API_KEY, provider=Provider.ANTHROPIC)
We should use the api_key variable, the access_token has been deprecated

2024-11-28 01:41 UTC, pulphix commented on examples/sample_anthropic.py
> +th = Toolhouse(access_token=TH_API_KEY, provider=Provider.ANTHROPIC)
We should use the api_key variable, the access_token has been deprecated

2024-11-28 01:41 UTC, pulphix commented on examples/sample_groq.py
> +th = Toolhouse(access_token=TH_API_KEY, provider="openai")
We should use the api_key variable, the access_token has been deprecated

2024-11-28 01:41 UTC, pulphix commented on examples/sample_groq_openai_client.py
> +th = Toolhouse(access_token=TH_API_KEY, provider="openai")
We should use the api_key variable, the access_token has been deprecated

2024-11-28 01:41 UTC, pulphix commented on examples/sample_groq_openai_client_stream.py
> +th = Toolhouse(access_token=TH_API_KEY, provider="openai")
We should use the api_key variable, the access_token has been deprecated

2024-11-28 01:41 UTC, pulphix commented on examples/sample_groq_stream.py
> +th = Toolhouse(access_token=TH_API_KEY, provider="openai")
We should use the api_key variable, the access_token has been deprecated

2024-11-28 01:41 UTC, pulphix commented on examples/sample_llamaindex.py
> +th = Toolhouse(access_token=TH_API_KEY, provider="llamaindex")
We should use the api_key variable, the access_token has been deprecated

2024-11-28 01:41 UTC, pulphix commented on examples/sample_openai.py
> +th = Toolhouse(access_token=TH_API_KEY, provider="openai")
We should use the api_key variable, the access_token has been deprecated

2024-11-28 01:41 UTC, pulphix commented on examples/sample_openai_stream.py
> +th = Toolhouse(access_token=TH_API_KEY, provider="openai")
We should use the api_key variable, the access_token has been deprecated

2024-11-28 01:41 UTC, pulphix commented on examples/sample_run_local_tools.py
> +th = Toolhouse(access_token=TH_API_KEY, provider=Provider.ANTHROPIC)
We should use the api_key variable, the access_token has been deprecated

2024-11-28 01:41 UTC, pulphix commented on examples/sample_run_local_tools_groq.py
> +th = Toolhouse(access_token=TH_API_KEY, provider="openai")
We should use the api_key variable, the access_token has been deprecated

2024-11-28 01:41 UTC, pulphix commented on examples/sample_run_local_tools_groq_stream.py
> +th = Toolhouse(access_token=TH_API_KEY, provider="openai")
We should use the api_key variable, the access_token has been deprecated

2024-11-28 01:41 UTC, pulphix commented on examples/sample_run_local_tools_openai.py
> +th = Toolhouse(access_token=TH_API_KEY, provider="openai")
We should use the api_key variable, the access_token has been deprecated

2024-11-28 01:41 UTC, pulphix commented on examples/sample_run_local_tools_openai_stream.py
> +th = Toolhouse(access_token=TH_API_KEY, provider="openai")
We should use the api_key variable, the access_token has been deprecated

2024-11-28 01:41 UTC, pulphix commented on examples/sample_run_local_tools_stream.py
> +th = Toolhouse(access_token=TH_API_KEY, provider=Provider.ANTHROPIC)
We should use the api_key variable, the access_token has been deprecated

2024-12-03 20:27 UTC, aaishikasb commented
The latest commit also addresses the typo identified in #12.

2024-12-03 21:48 UTC, VinciGit00 commented
Hi @aaishikasb can you add me as co author?

2024-12-03 21:56 UTC, aaishikasb commented
> Hi @aaishikasb can you add me as co author?

Can you send me your GitHub email via Discord? Preferably the private one that GitHub provides!

2024-12-04 17:30 UTC, iamdaniele requested changes
There are a bunch of files where `access_token` should be `api_key` instead.

Also note that SDKs are smart and can autodetect their API key if they're already set up as environment variables. This removes the need to call `os.getenv` and explicitly set an API Key if they already have the following env variables set up in their system:

- `TOOLHOUSE_API_KEY` (Toolhouse)
- `OPENAI_API_KEY` (OpenAI)
- `ANTHROPIC_API_KEY` (Anthropic)
- `GROQCLOUD_API_KEY` (Groq)

2024-12-04 17:30 UTC, iamdaniele commented on README.md
> +client = OpenAI(access_token=OAI_KEY)
Change this to

```
client = OpenAI(api_key=OAI_KEY)
```

2024-12-04 17:30 UTC, iamdaniele commented on examples/sample_anthropic_stream.py
> +    model="gpt-4-turbo",
The line you removed was actually the right one (`gpt-4-turbo` is an OpenAI model but this is an Anthropic example). Change this to:

```
model="claude-3-5-sonnet-20240620"
```

2024-12-04 17:30 UTC, iamdaniele commented on examples/sample_anthropic_stream.py
> +            model="gpt-4-turbo",
The line you removed was actually the right one (`gpt-4-turbo` is an OpenAI model but this is an Anthropic example). Change this to:

```
model="claude-3-5-sonnet-20240620"
```

2024-12-04 17:30 UTC, iamdaniele commented on examples/sample_groq.py
> +client = Groq(api_key=GROQ_TOKEN)
These are API keys, not tokens. API keys are long lived or never expired until invalidated by the users. Tokens are short lived and usually expire automatically.

```
GROQ_API_KEY = os.getenv("GROQCLOUD_API_KEY")
client = Groq(api_key=GROQ_API_KEY)
```

2024-12-04 17:30 UTC, iamdaniele commented on examples/sample_groq_openai_client.py
>  )
These are API keys, not tokens. API keys are long lived or never expired until invalidated by the users. Tokens are short lived and usually expire automatically.

```
GROQ_API_KEY = os.getenv("GROQCLOUD_API_KEY")
client = OpenAI(
   api_key=GROQ_API_KEY
   # Rest of your code
```

2024-12-04 17:30 UTC, iamdaniele commented on examples/sample_groq_openai_client_stream.py
>  )
These are API keys, not tokens. API keys are long lived or never expired until invalidated by the users. Tokens are short lived and usually expire automatically.

```
GROQ_API_KEY = os.getenv("GROQCLOUD_API_KEY")
client = OpenAI(
   api_key=GROQ_API_KEY
   # Rest of your code
```

2024-12-04 17:30 UTC, iamdaniele commented on examples/sample_groq_stream.py
Same as other comment, change `GROQ_TOKEN` to `GROQ_API_KEY` (or similar name, but make sure to use the API_KEY suffix)

2024-12-04 17:30 UTC, iamdaniele commented on examples/sample_openai.py
> +client = OpenAI(access_token=OAI_KEY)
`client = OpenAI(api_key=OAI_KEY)`

2024-12-04 17:30 UTC, iamdaniele commented on examples/sample_openai_stream.py
> +client = OpenAI(access_token=OAI_KEY)
`client = OpenAI(api_key=OAI_KEY)`

2024-12-04 17:30 UTC, iamdaniele commented on examples/sample_run_local_tools_groq.py
> +GROQ_TOKEN = os.getenv("GROQCLOUD_API_KEY")
```
GROQ_API_KEY = os.getenv("GROQCLOUD_API_KEY")
```

2024-12-04 17:30 UTC, iamdaniele commented on examples/sample_run_local_tools_groq.py
> +client = Groq(api_key=GROQ_TOKEN)
```
client = Groq(api_key=GROQ_API_KEY)
```

2024-12-04 17:30 UTC, iamdaniele commented on examples/sample_run_local_tools_groq_stream.py
> +client = Groq(api_key=GROQ_TOKEN)
Same as above, replace `TOKEN` for `API_KEY`

2024-12-04 17:30 UTC, iamdaniele commented on examples/sample_run_local_tools_groq_stream.py
> +    model="gpt-4o", messages=messages, tools=th.get_tools() + local_tools, stream=True # Retrieve tools installed from Toolhouse
`gpt-4o` is an OpenAI model but the code uses Groq, and Groq does not serve OpenAI models. You should change this to any of the [Groq supported models](https://console.groq.com/docs/models) (suggest you use Llama 3.1 or 3.2)

2024-12-04 17:30 UTC, iamdaniele commented on examples/sample_run_local_tools_groq_stream.py
> +response = client.chat.completions.create(model="gpt-4o", messages=messages, tools=th.get_tools() + local_tools) # Retrieve tools installed from Toolhouse
`gpt-4o` is an OpenAI model but the code uses Groq, and Groq does not serve OpenAI models. You should change this to any of the [Groq supported models](https://console.groq.com/docs/models) (suggest you use Llama 3.1 or 3.2)

2024-12-04 17:30 UTC, iamdaniele commented on examples/sample_run_local_tools_openai.py
> +client = OpenAI(access_token=OAI_KEY)
`client = OpenAI(api_key=OAI_KEY)`

2024-12-04 17:30 UTC, iamdaniele commented on examples/sample_run_local_tools_openai_stream.py
> +client = OpenAI(access_token=OAI_KEY)
`client = OpenAI(api_key=OAI_KEY)`

2024-12-04 17:53 UTC, aaishikasb commented
Addressed the requested changes in the aforementioned commits!

2024-12-06 08:46 UTC, VinciGit00 commented
> GitHub

can I have you discord username?

2024-12-10 23:38 UTC, orliesaurus approved these changes
Approved

2024-12-10 23:39 UTC, merged